### ISSUE TITLE
训练时遇到的问题

### ISSUE THREAD

**Issue by sunmeng7** [wcy-cs/SFMNet#12]
```
/opt/conda/envs/imagen/lib/python3.8/site-packages/torch/nn/modules/loss.py:96: UserWarning: Using a target size (torch.Size([8, 3, 128, 128])) that is different to the input size (torch.Size([8, 3, 32, 32])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.l1_loss(input, target, reduction=self.reduction)
Traceback (most recent call last):
  File "/home/sunmeng/superR/SFMNet/main_two.py", line 131, in <module>
    train_model(model, trainset, i, args)
  File "/home/sunmeng/superR/SFMNet/main_two.py", line 111, in train_model
    loss = criterion1(sr['img_out'], data['img_gt']) + \
  File "/opt/conda/envs/imagen/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/imagen/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 96, in forward
    return F.l1_loss(input, target, reduction=self.reduction)
  File "/opt/conda/envs/imagen/lib/python3.8/site-packages/torch/nn/functional.py", line 3248, in l1_loss
    expanded_input, expanded_target = torch.broadcast_tensors(input, target)
  File "/opt/conda/envs/imagen/lib/python3.8/site-packages/torch/functional.py", line 73, in broadcast_tensors
    return _VF.broadcast_tensors(tensors)  # type: ignore[attr-defined]
RuntimeError: The size of tensor a (32) must match the size of tensor b (128) at non-singleton dimension 3
```

您好，我训练的时候遇到这样的报错，要怎么解决呢
报错的位置
```
loss = criterion1(sr['img_out'], data['img_gt']) + \
               args.fft_weight * amploss(sr['img_fre'], data['img_gt']) + args.fft_weight * phaloss(
            sr['img_fre'],
            data[
                'img_gt']) + \
               criterion1(sr['img_fre'], data['img_gt'])
```

**Comment by wcy-cs** [comment]
您好，这个看起来好像是维度的问题，本文需要将低分辨率图像插值到高分辨率空间再送入模型中
